### ISSUE TITLE
Setup CI to avoid uncompileable code

### ISSUE THREAD

**Issue by eiaro** [Mr-Markus/ZigbeeNet#5]
Setup a CI to avoid code that cannot compile to enter master branch.

**Comment by eiaro** [comment]
I am not able to setup this for you. If you choose to use AppVeyor you just access their page and activate it using your GitHub credentials. Then on the Projects page you add this repository.

Then add a file named `appveyor.yml` with the following content and it should be setup to build.

```
version: 1.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu1804
install:
  - git submodule update --init --recursive
before_build:
  - nuget restore unpi-net/src/UnpiNet.sln
  - nuget restore src/ZigbeeNet.sln
build:
  verbosity: minimal
  project: src/ZigbeeNet.sln
```
